[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
optimizer = true
optimizer_runs = 2000
via_ir = true

fs_permissions = [{ access = "read", path = "./out"}]

[rpc_endpoints]
bsc-testnet = "${BINANCE_TESTNET_RPC_URL}"

[etherscan]
bsc-testnet = {key = "${bscscan_api_key}" , chain = "bsc-testnet"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
